[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
# Terminal library
crossterm = "0.27.0"
# Compute unicode printed width
unicode-width = "0.1"
# Compute unicode grapheme
unicode-segmentation = "1.10"
# Bitflags helper macro
bitflags = "2.3"